### ISSUE TITLE
uint missing from dtypes

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#254]
https://schema-language.readthedocs.io/en/latest/specification_language_description.html#dtype

The dtypes table includes `int`, which is equal to `int32`, but no `uint`. Is there a reason for this? Could we add support for `uint`?

**Comment by oruebel** [comment]
Looking at https://github.com/hdmf-dev/hdmf/blob/99ce39e96cab7330d37e739efd0f6451eb3da1f0/src/hdmf/spec/spec.py#L25-L43 or more specifically https://github.com/hdmf-dev/hdmf/blob/99ce39e96cab7330d37e739efd0f6451eb3da1f0/src/hdmf/spec/spec.py#L37 ``uint`` maps to ``uint32``.  I.e., I think this should already works and table in the docs just needs to be updated to add ``unit`` as an alternative for ``uint32``

**Comment by bendichter** [comment]
when I try to use `uint` I get the following error:

```python
Traceback (most recent call last):
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 934, in __add_datasets
    data, dtype = self.convert_dtype(spec, attr_value)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 427, in convert_dtype
    raise ValueError(msg)
ValueError: unrecognized dtype: uint -- cannot convert value
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-2127a30bba2b>", line 2, in <module>
    io.write(nwbfile)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/backends/hdf5/h5tools.py", line 196, in write
    call_docval_func(super(HDF5IO, self).write, kwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 274, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/backends/io.py", line 39, in write
    f_builder = self.__manager.build(container, source=self.__source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 159, in build
    result = self.__type_map.build(container, self, source=source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 1546, in build
    builder = attr_map.build(container, manager, builder=builder, source=getargs('source', kwargs))
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 762, in build
    self.__add_groups(builder, self.__spec.groups, container, manager, source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 967, in __add_groups
    self.__add_groups(sub_builder, spec.groups, container, build_manager, source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 978, in __add_groups
    self.__add_containers(builder, spec, attr_value, build_manager, source, container)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 993, in __add_containers
    rendered_obj = build_manager.build(value, source=source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 159, in build
    result = self.__type_map.build(container, self, source=source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 1546, in build
    builder = attr_map.build(container, manager, builder=builder, source=getargs('source', kwargs))
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 762, in build
    self.__add_groups(builder, self.__spec.groups, container, manager, source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 978, in __add_groups
    self.__add_containers(builder, spec, attr_value, build_manager, source, container)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 993, in __add_containers
    rendered_obj = build_manager.build(value, source=source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 159, in build
    result = self.__type_map.build(container, self, source=source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 1546, in build
    builder = attr_map.build(container, manager, builder=builder, source=getargs('source', kwargs))
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 762, in build
    self.__add_groups(builder, self.__spec.groups, container, manager, source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 978, in __add_groups
    self.__add_containers(builder, spec, attr_value, build_manager, source, container)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 1026, in __add_containers
    self.__add_containers(builder, spec, container, build_manager, source, parent_container)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 993, in __add_containers
    rendered_obj = build_manager.build(value, source=source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 159, in build
    result = self.__type_map.build(container, self, source=source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 1546, in build
    builder = attr_map.build(container, manager, builder=builder, source=getargs('source', kwargs))
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 761, in build
    self.__add_datasets(builder, self.__spec.datasets, container, manager, source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 938, in __add_datasets
    raise_from(Exception(msg), ex)
  File "<string>", line 3, in raise_from
Exception: could not convert 'faces' for Surface 'test'
```

I believe the issue is here:

https://github.com/hdmf-dev/hdmf/blob/99ce39e96cab7330d37e739efd0f6451eb3da1f0/src/hdmf/build/map.py#L345-L369

**Comment by oruebel** [comment]
I think that's probably right. Did you try adding ``"uint": np.uint32`` to the ``ObjectMapper.__dtypes``?

**Comment by bendichter** [comment]
no, I didn't try that. It's not a huge deal for me as using `uint32` works just fine.
